interntask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timedashboard.urls')), # add urls of timedashboard app.
]

timedashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, LoginView


app_name = 'timedashboard'

urlpatterns = [
    path('', views.AllTimings.as_view(), name = 'listtiming'),
    path('signup/', views.Signup.as_view(), name = 'signup'),
    path('createtime/', views.CreateTiming.as_view(), name = 'createtime'),
    path('endtime/<int:pk>/', views.EndTask.as_view(), name = 'endtask'),
    path('login/', LoginView.as_view(template_name = 'timedashboard/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
]

timedashboard/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
	name = models.CharField(max_length = 200, unique = True)

	def __str__(self):
		return self.name

class Timing(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	project = models.ForeignKey(Project, on_delete = models.CASCADE)
	task = models.CharField(max_length = 200) # task name
	start = models.DateTimeField(auto_now_add = True) # start time will be the time of creating an object
	end = models.DateTimeField(default = None, null = True)

	def __str__(self):
		return self.task

timedashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Timing, Project


class SignupForm(forms.ModelForm):
	"""
		override the password field to get a change input type of password.
		add verify_password field to verify to user's password.
	"""
	password = forms.CharField(widget = forms.PasswordInput,label = "Password")
	verify_password = forms.CharField(widget = forms.PasswordInput,label = "Password (again)")
	
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email','password']

	def clean(self):
		# override clean function to verify extra conditions(verify  password).
		cleaned_data = super(SignupForm, self).clean()
		if 'password' in self.cleaned_data and 'verify_password' in self.cleaned_data:
			if self.cleaned_data['password'] != self.cleaned_data['verify_password']: # password and verify_password field should be the same
				raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
			else:
				del cleaned_data['verify_password'] # non-useful field removed.
				return self.cleaned_data
	
	def save(self, commit = True):
		user = super(SignupForm, self).save(commit = False)
		user.set_password(self.cleaned_data['password']) # set password in user instance
		if commit is True:
			user.save()
		return user


class CreateTimingForm(forms.ModelForm):
	class Meta:
		model = Timing
		fields = ['project', 'task']

	def __init__(self, *args,**kwargs):
		super().__init__(*args, **kwargs)
		# get all projects from Project table
		self.fields['project'].queryset = Project.objects.all()

timedashboard/views.py
import datetime

from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, FormView, DetailView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.urls import reverse_lazy

from .forms import SignupForm, CreateTimingForm
from .models import Timing, Project


class CreateTiming(LoginRequiredMixin, CreateView):
	"""
		CreateView
			I used CreateView to create a new instance of work/time.
			Createview that provides the functionality to create new objects very easily.

		LoginRequiredMixin
			Used to implement login required functionality in the class and also it allows us to specify a URL for login.
	"""
	template_name = 'timedashboard/createtime.html'
	login_url = '/signup/' # to login
	form_class = CreateTimingForm
	allow_empty = True
	success_url = reverse_lazy('timedashboard:listtiming')  # go to this URL after creating new object/work

	def form_valid(self, form):
		new_work = form.save(commit = False)
		new_work.user = self.request.user
		new_work.save()
		return HttpResponseRedirect(self.success_url)


class AllTimings(LoginRequiredMixin, ListView):
	"""
		ListView
			I used ListView to print/show all the previous timings.
			ListView provides a list- object_list which has queryset data.

		LoginRequiredMixin
			Used to implement login required(user must be login) functionality in the class and also it allows us to specify a URL for login.
	"""
	template_name = 'timedashboard/timing_list.html'
	allow_empty = True
	login_url = '/signup/'

	def get_queryset(self):
		# all the previous timings.
		return Timing.objects.filter(user = self.request.user).select_related('project').order_by("start").reverse()


class EndTask(DetailView):
	
	def get(self, request, pk):
		# end current timing.
		curr_task = Timing.objects.filter(pk = pk).first()
		curr_task.end = datetime.datetime.now()
		curr_task.save(update_fields = ['end'])
		return redirect(reverse('timedashboard:listtiming',))


class Signup(CreateView):
	"""
		CreateView
			I used CreateView to create a new user instance and after creating a new user it will go to create a timing instance.
			CareteView provides functionality to create new objects very easily.
	"""
	form_class = SignupForm
	template_name = 'timedashboard/signup.html'
	success_url = reverse_lazy('timedashboard:createtime')
	
	def form_valid(self, form):
		valid = super(Signup, self).form_valid(form)
		username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password')
		new_user = authenticate(username = username, password = password)
		login(self.request, new_user) # login new user
		return valid

timedashboard/templates/timedashboard/createtime.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>New Work</title>
    <meta charset="UTF-8">    
</head>
<body>
    <a href="{% url 'timedashboard:listtiming' %}"> <button>Previous Timings</button></a>
    <a href="{% url 'timedashboard:logout' %}"> <button>Logout </button></a>
    <form method="POST"> 
        {% csrf_token %} 
      
        {{ form.as_p }} 
          
        <input type="submit" value="Submit"> 
    </form> 
</body>
</html>

timedashboard/templates/timedashboard/login.html
<!DOCTYPE html>
<html lang="en">
<head>
      <title>Login</title>
</head>
<body>
    <form method="POST"> 
        {% csrf_token %} 
      
        {{ form.as_p }} 
          
        <input type="submit" value="Submit"> 
        <a href="{% url 'timedashboard:signup' %}"> Haven't an account?</a>
    </form> 
</body>
</html>

timedashboard/templates/timedashboard/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
      <title>Signup</title>
</head>
<body>
    <form method="POST"> 
        {% csrf_token %} 
      
        {{ form.as_p }} 
          
        <input type="submit" value="Submit"> 
        <a href="{% url 'timedashboard:login' %}"> Already have an account?</a>
    </form> 
</body>
</html>

timedashboard/templates/timedashboard/timing_list.html
<!DOCTYPE html>
<html lang="en">
<head>
      <title>Home</title>
</head>
<body>
    <a href="{% url 'timedashboard:createtime' %}"> <button> Start New Work</button></a>
	<a href="{% url 'timedashboard:logout' %}"> <button>Logout </button></a>
	<h2>{{request.user.first_name}} {{request.user.last_name}}</h2>
	<h3 style="padding:0 10px 0 10px;">Complete List</h3>
	<table>
		<tr>
			<td style="text-align: center; padding:0 10px 0 10px;"><b>Project Name</b></td>
			<td style="text-align: center; padding:0 10px 0 10px;"><b>Task Name</b></td>
			<td style="text-align: center; padding:0 10px 0 10px;"><b>Start Time</b></td>
			<td style="text-align: center; padding:0 10px 0 10px;"><b>End Time</b></td>
		</tr>
		{% for timing in object_list %}
			<tr>
				<td style="text-align: center; padding:0 10px 0 10px;">{{timing.project.name}}</td>
				<td style="text-align: center; padding:0 10px 0 10px;">{{timing.task}}</td>
				<td style="text-align: center; padding:0 10px 0 10px;">{{timing.start}}</td>
				{% if timing.end is None %}
					<td style="text-align: center; padding:0 10px 0 10px;"><a href="{% url 'timedashboard:endtask' pk=timing.pk %}"> <button>End Task</button></a></td>
				{% else %}
					<td style="text-align: center; padding:0 10px 0 10px;">{{timing.end}}</td>
				{% endif %}
			</tr>
			{% empty %}
		    <h3>No timings yet.</h3>
		{% endfor %}

	</table>
</body>
</html>